import type { SidebarsConfig } from "@docusaurus/plugin-content-docs"

const sidebars: SidebarsConfig = {
	autoSidebar: [{ type: "autogenerated", dirName: "." }],
	// 指南页
	guides: [
		{
			type: "category",
			label: "介绍",
			items: [
				{ type: "doc", id: "guides/intro/intro" },
				{ type: "doc", id: "guides/intro/design" },
			],
		},
		{
			type: "category",
			label: "开发",
			items: [
				{ type: "doc", id: "guides/usage/quick-start" },
				{ type: "doc", id: "guides/usage/multi-lang" },
				{ type: "doc", id: "guides/usage/light-dark-mode" },
				{ type: "doc", id: "guides/usage/theme" },
			],
		},
		{
			type: "category",
			label: "其他",
			items: [
				{ type: "doc", id: "guides/others/tech-stack" },
				{ type: "doc", id: "guides/others/faq" },
			],
		},
	],
	components: [{ type: "autogenerated", dirName: "components" }],
}

export default sidebars
